name: flutter_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  rxdart: ^0.24.1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMono-Regular.ttf
        - asset: assets/fonts/UbuntuMono-Italic.ttf
          style: italic
        - asset: assets/fonts/UbuntuMono-Bold.ttf
          weight: 700